name: snapshot

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y \
              shellcheck \
              pdftk \
              poppler-utils \
              imagemagick

          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install \
              shellcheck \
              pdftk-java \
              poppler \
              imagemagick
          fi

      - name: Install bashunit
        shell: bash
        run: |
          curl -s https://bashunit.com/install.sh | bash

      - name: Build and test
        shell: bash
        run: make test
